### ISSUE TITLE
Camptix Registration form is not loading

### ISSUE THREAD

**Issue by sanyogs** [wpindiaorg/camptix-indian-payments#10]
As with latest pull #9 tested code to check core functionality of plugin its blocking form.

**Comment by ravinderk** [comment]
@sanyogs Script was loading on WordPress page, so `js` is restricting any form submission. Can you now test latest `master` branch code

**Comment by sanyogs** [comment]
I have tested there was diercotry tree issue which is you have been fixed in latest commit
