### ISSUE TITLE
Razorpay After Checkout not redirecting

### ISSUE THREAD

**Issue by sanyogs** [wpindiaorg/camptix-indian-payments#11]
After filling form and selecting Razorpay as payment method it dont redirect to payment method
getting following message

{"success":true,"data":{"items":[{"id":410,"name":"test123","description":"sdgsdg","quantity":"1","price":10}],"total":10,"coupon":null,"attendee_id":611,"fullname":"Sanyog Shelar","email":"sanyog@version-next.com","phone":"993080966","total_in_paisa":1000,"return_url":"http:\/\/vntservers.net\/client\/pp\/about-us\/?tix_action=payment_return&tix_payment_token=d23b4cb867f8309cbe8001bff3bfe2eb&tix_payment_method=camptix_razorpay","popup_title":"payment"}}

**Comment by sanyogs** [comment]
i see there is no checkout URL please check function template_redirect()

**Comment by ravinderk** [comment]
@sanyogs Working fine for me. Can you create a video which explains what is causing you from successful checkout?

**Comment by sanyogs** [comment]
I have tested this with latest file and its seems to fixed.
