### ISSUE TITLE
Forcing 10 Digit Mobile number

### ISSUE THREAD

**Issue by vachan** [wpindiaorg/camptix-indian-payments#13]
It is really not advisable to force the user to input only 10 digit number.

@sanyogs : As mentioned previously also, If there is a restriction from Instamojo, deal with the requirement at the class level by adjusting the string with `substr($extra_info['phone'],-10)` file:class-camptix-payment-method-instamojo | line:303

**Comment by vachan** [comment]
Please read my comment, I have provided a solution it the comment itself.
let the user type he full regular mobile number.

Options to deal with the number:
===
1) Write a function, where in we check if the number is entered starting with `+` and if so check if the following is `91`, if so we are sorted to get the accurate value by using `substr($extra_info['phone'],-10)` which will give us the last ten digits of the number. 

2) Don't
First only extract numbers by 
`preg_match_all( '!\d+!', $extra_info['phone'], $phone);
if ( 11 >= strlen( $phone ) ) {
  $attendee_phone = substr( $phone, -10 );
} else {
  $attendee_phone = str_pad( $phone, 10, '9', STR_PAD_LEFT);
}`

If you don't want to pad the number _(not use the *else*)_, you can choose to return and error for, minimum *10 digits required*.

**Comment by sanyogs** [comment]
@vachan 
I have written something like this.

```
$phone = ltrim($extra_info['phone'],'0');
            if(strlen($phone)>10){
                $phoneno = substr($phone,0,10);
            }elseif(strlen($phone)<=9){
                $phoneno = '9999999999';
            }else{
                $phoneno = $phone;
            }
```

Please confirm so i can update same

**Comment by vachan** [comment]
@sanyogs 

`substr($phone,0,10)` : This is take the first 10 digits; so if the user types, +919819833887; then as per your use the value returned will be **+919819833** which is again _not appropriate_.

`strlen($phone)<=9` : You are forcing a false info, even if manipulated; atleast the `str_pad` will help keep the values close to the users input.
`str_pad( $phone, 10, '9', STR_PAD_LEFT)`

The last `else` can be avoided, by the login that if the conditions are safe, no need to change the value.

My suggestions:
===
```
$attendee_phone = ltrim($extra_info['phone'],'0');
            if ( 10 > strlen($phone) ) {
                $attendee_phone = substr( $phone, -10 );
            } elseif ( 9 <= strlen($phone) ) {
                 $attendee_phone = str_pad( $phone, 10, '9', STR_PAD_LEFT);
            }
```
Final number String: `$attendee_phone`

**Comment by vachan** [comment]
Also just updated as per: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#yoda-conditions

**Comment by sanyogs** [comment]
#29 has released for this please verify and merge.
