### ISSUE TITLE
WordPress database error

### ISSUE THREAD

**Issue by vachan** [wpindiaorg/camptix-indian-payments#14]
If you will check the `error_log` file, you may notice two log entries:
`WordPress database error Column 'object_id' cannot be null for query INSERT INTO .....`

After every tranaction made via this plugins' payment platforms

**Comment by ravinderk** [comment]
@vachan Does this happen with both payment gateway or any one?

**Comment by vachan** [comment]
@ravinderk Both the Gateways...
I think it is being triggered after the ticket is created as a draft and before executing the gateway class.

**Comment by sanyogs** [comment]
can you send the video for this. As i have try to debug and run but nothing getting

**Comment by vachan** [comment]
It is an `error_log` they tend to happen as the server level not at the client level. So there is no frontend to screencast.

as for the full log-entry (actual values are _hassed ###_):
> WordPress database error Column 'object_id' cannot be null for query INSERT INTO `wp_camptix_log` (`blog_id`, `object_id`, `message`, `data`, `section`) VALUES (5, NULL, 'Running payment_notify. Request data attached.', '{\"tix_action\":\"payment_notify\",\"tix_payment_token\":\"################################\",\"tix_payment_method\":\"instamojo\",\"payment_id\":\"MOJO################\",\"status\":\"Credit\",\"shorturl\":\"\",\"longurl\":\"https:\\/\\/test.instamojo.com\\/@kdcpay\\/##############################\",\"purpose\":\"CampTix Indian Payments\",\"amount\":\"306.73\",\"fees\":\"5.70\",\"currency\":\"INR\",\"buyer\":\"vachan@kdc.in\",\"buyer_name\":\"Vachan Kudmule\",\"buyer_phone\":\"#########\",\"payment_request_id\":\"##############################\",\"mac\":\"##############################\"}', 'payment') made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, CampTix_Payment_Method_Instamojo->template_redirect, CampTix_Payment_Method_Instamojo->payment_notify, CampTix_Payment_Method->__call, CampTix_Plugin->log, do_action('camptix_log_raw'), WP_Hook->do_action, WP_Hook->apply_filters, CampTix_Network_Tools->camptix_log_raw

>

**Comment by sanyogs** [comment]
Vachan if you could send video of this troublshoot it will help to detect the issue.

**Comment by vachan** [comment]
Requested Video: https://cloudup.com/cEqq1ijrH0H

**error_log** File:
===
> [26-Jul-2017 07:17:45 UTC] CampTix (camptix.kdclabs.in): Created attendee draft.
> [26-Jul-2017 07:18:20 UTC] WordPress database error Column 'object_id' cannot be null for query INSERT INTO `kdcwp_camptix_log` (`blog_id`, `object_id`, `message`, `data`, `section`) VALUES (5, NULL, 'Running payment_notify. Request data attached.', '{\"tix_action\":\"payment_notify\",\"tix_payment_token\":\"dee2394ab86907d643cd757ed2ca98f4\",\"tix_payment_method\":\"instamojo\",\"payment_id\":\"MOJO7726005A95615235\",\"status\":\"Credit\",\"shorturl\":\"\",\"longurl\":\"https:\\/\\/test.instamojo.com\\/@kdcpay\\/76730198218e489fba832231eb34c813\",\"purpose\":\"CampTix Indian Payments\",\"amount\":\"102.25\",\"fees\":\"1.90\",\"currency\":\"INR\",\"buyer\":\"vachan@kdc.in\",\"buyer_name\":\"Vachan Kudmule\",\"buyer_phone\":\"+919819833887\",\"payment_request_id\":\"76730198218e489fba832231eb34c813\",\"mac\":\"8ec4f72b832900102c09569bcc782919707d16ae\"}', 'payment') made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, CampTix_Payment_Method_Instamojo->template_redirect, CampTix_Payment_Method_Instamojo->payment_notify, CampTix_Payment_Method->__call, CampTix_Plugin->log, do_action('camptix_log_raw'), WP_Hook->do_action, WP_Hook->apply_filters, CampTix_Network_Tools->camptix_log_raw
> [26-Jul-2017 07:18:20 UTC] CampTix (camptix.kdclabs.in): Running payment_notify. Request data attached.
> [26-Jul-2017 07:18:20 UTC] WordPress database error Column 'object_id' cannot be null for query INSERT INTO `kdcwp_camptix_log` (`blog_id`, `object_id`, `message`, `data`, `section`) VALUES (5, NULL, 'Running payment_notify. Server data attached.', '{\"SERVER_SOFTWARE\":\"Apache\",\"REQUEST_URI\":\"\\/indina-payments\\/?tix_action=payment_notify&tix_payment_token=dee2394ab86907d643cd757ed2ca98f4&tix_payment_method=instamojo\",\"CONTENT_LENGTH\":\"385\",\"CONTENT_TYPE\":\"application\\/x-www-form-urlencoded\",\"CONTEXT_DOCUMENT_ROOT\":\"\\/home\\/kdclabs\\/public_html\\/camptix\",\"CONTEXT_PREFIX\":\"\",\"DOCUMENT_ROOT\":\"\\/home\\/kdclabs\\/public_html\\/camptix\",\"GATEWAY_INTERFACE\":\"CGI\\/1.1\",\"HTTPS\":\"on\",\"HTTP_ACCEPT\":\"*\\/*\",\"HTTP_ACCEPT_ENCODING\":\"gzip, deflate\",\"HTTP_CONNECTION\":\"keep-alive\",\"HTTP_HOST\":\"camptix.kdclabs.in\",\"HTTP_USER_AGENT\":\"Instamojo-Webhook\\/1.0\",\"HTTP_X_NEWRELIC_ID\":\"VQcBVFNXGwEBV1RUDwgD\",\"HTTP_X_NEWRELIC_TRANSACTION\":\"PxQGAl8HXQFSUAJbVlIFXlAJFB8EBw8RVU4aU1sBUFcBBw0CCABQUFwCD0NKQQ0GCFFTAFYEFTs=\",\"HTTP_X_WEBHOOK_ATTEMPT\":\"1\",\"HTTP_X_WEBHOOK_ID\":\"4a85bb99-7aad-4361-b4bf-c1e77b7a6042\",\"HTTP_X_WEBHOOK_SIGNATURE\":\"8ec4f72b832900102c09569bcc782919707d16ae\",\"PATH\":\"\\/bin:\\/usr\\/bin\",\"QUERY_STRING\":\"tix_action=payment_notify&tix_payment_token=dee2394ab86907d643cd757ed2ca98f4&tix_payment_method=instamojo\",\"REDIRECT_HTTPS\":\"on\",\"REDIRECT_QUERY_STRING\":\"tix_action=payment_notify&tix_payment_token=dee2394ab86907d643cd757ed2ca98f4&tix_payment_method=instamojo\",\"REDIRECT_SSL_TLS_SNI\":\"camptix.kdclabs.in\",\"REDIRECT_STATUS\":\"200\",\"REDIRECT_UNIQUE_ID\":\"WXhCPAlzeyjKKDNb87BjGAAAABM\",\"REDIRECT_URL\":\"\\/indina-payments\\/\",\"REMOTE_ADDR\":\"52.90.54.216\",\"REMOTE_PORT\":\"50838\",\"REQUEST_METHOD\":\"POST\",\"REQUEST_SCHEME\":\"https\",\"SCRIPT_FILENAME\":\"\\/home\\/kdclabs\\/public_html\\/camptix\\/index.php\",\"SCRIPT_NAME\":\"\\/index.php\",\"SERVER_ADDR\":\"108.163.221.91\",\"SERVER_ADMIN\":\"webmaster@camptix.kdclabs.in\",\"SERVER_NAME\":\"camptix.kdclabs.in\",\"SERVER_PORT\":\"443\",\"SERVER_PROTOCOL\":\"HTTP\\/1.1\",\"SERVER_SIGNATURE\":\"\",\"SSL_TLS_SNI\":\"camptix.kdclabs.in\",\"TZ\":\"Asia\\/Kolkata\",\"UNIQUE_ID\":\"WXhCPAlzeyjKKDNb87BjGAAAABM\",\"PHP_SELF\":\"\\/index.php\",\"REQUEST_TIME_FLOAT\":\"1501053500.4226\",\"REQUEST_TIME\":\"1501053500\",\"argv\":[\"tix_action=payment_notify&tix_payment_token=dee2394ab86907d643cd757ed2ca98f4&tix_payment_method=instamojo\"],\"argc\":\"1\"}', 'payment') made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, CampTix_Payment_Method_Instamojo->template_redirect, CampTix_Payment_Method_Instamojo->payment_notify, CampTix_Payment_Method->__call, CampTix_Plugin->log, do_action('camptix_log_raw'), WP_Hook->do_action, WP_Hook->apply_filters, CampTix_Network_Tools->camptix_log_raw
> [26-Jul-2017 07:18:20 UTC] CampTix (camptix.kdclabs.in): Running payment_notify. Server data attached.
> [26-Jul-2017 07:18:20 UTC] CampTix (camptix.kdclabs.in): New tix_attendee created.
> [26-Jul-2017 07:18:20 UTC] CampTix (camptix.kdclabs.in): Payment result for .
> [26-Jul-2017 07:18:20 UTC] CampTix (camptix.kdclabs.in): Attendee status has been changed to publish
> [26-Jul-2017 07:18:20 UTC] CampTix (camptix.kdclabs.in): Sent a ticket and receipt to vachan@kdc.in.
> [26-Jul-2017 07:18:20 UTC] WordPress database error Column 'object_id' cannot be null for query INSERT INTO `kdcwp_camptix_log` (`blog_id`, `object_id`, `message`, `data`, `section`) VALUES (5, NULL, 'Sent e-mail to vachan@kdc.in.', '{\"to\":\"vachan@kdc.in\",\"subject\":\"Your Ticket to CampTix Indian Payments\",\"message\":\"Hi there!\\n\\nYou have purchased the following ticket:\\n\\n* INR Demo (\\u20b9 100.00) x1 = \\u20b9 100.00\\n* Total: \\u20b9 100.00\\n\\nYou can edit the information for the purchased ticket at any time before the event, by visiting the following link:\\n\\nhttps:\\/\\/camptix.kdclabs.in\\/indina-payments\\/?tix_action=access_tickets&tix_access_token=36454f311cdb2e2d08a48e77844f8298#tix\\n\\nLet us know if you have any questions!\",\"headers\":[\"Reply-To: CampTix Indian Payments <labs@kdc.in>\"]}', 'email') made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, CampTix_Payment_Method_Instamojo->template_redirect, CampTix_Payment_Method_Instamojo->payment_notify, CampTix_Payment_Method->__call, CampTix_Plugin->payment_result, CampTix_Plugin->email_tickets, CampTix_Plugin->wp_mail, CampTix_Plugin->log, do_action('camptix_log_raw'), WP_Hook->do_action, WP_Hook->apply_filters, CampTix_Network_Tools->camptix_log_raw
> [26-Jul-2017 07:18:20 UTC] CampTix (camptix.kdclabs.in): Sent e-mail to vachan@kdc.in.
> [26-Jul-2017 07:18:21 UTC] WordPress database error Column 'object_id' cannot be null for query INSERT INTO `kdcwp_camptix_log` (`blog_id`, `object_id`, `message`, `data`, `section`) VALUES (5, NULL, 'Running payment_return. Request data attached.', '{\"tix_action\":\"payment_return\",\"tix_payment_token\":\"dee2394ab86907d643cd757ed2ca98f4\",\"tix_payment_method\":\"instamojo\",\"payment_id\":\"MOJO7726005A95615235\",\"payment_request_id\":\"76730198218e489fba832231eb34c813\"}', 'payment') made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, CampTix_Payment_Method_Instamojo->template_redirect, CampTix_Payment_Method_Instamojo->payment_return, CampTix_Payment_Method->__call, CampTix_Plugin->log, do_action('camptix_log_raw'), WP_Hook->do_action, WP_Hook->apply_filters, CampTix_Network_Tools->camptix_log_raw
> [26-Jul-2017 07:18:21 UTC] CampTix (camptix.kdclabs.in): Running payment_return. Request data attached.
> [26-Jul-2017 07:18:21 UTC] WordPress database error Column 'object_id' cannot be null for query INSERT INTO `kdcwp_camptix_log` (`blog_id`, `object_id`, `message`, `data`, `section`) VALUES (5, NULL, 'Running payment_return. Server data attached.', '{\"SERVER_SOFTWARE\":\"Apache\",\"REQUEST_URI\":\"\\/indina-payments\\/?tix_action=payment_return&tix_payment_token=dee2394ab86907d643cd757ed2ca98f4&tix_payment_method=instamojo&payment_id=MOJO7726005A95615235&payment_request_id=76730198218e489fba832231eb34c813\",\"CONTEXT_DOCUMENT_ROOT\":\"\\/home\\/kdclabs\\/public_html\\/camptix\",\"CONTEXT_PREFIX\":\"\",\"DOCUMENT_ROOT\":\"\\/home\\/kdclabs\\/public_html\\/camptix\",\"GATEWAY_INTERFACE\":\"CGI\\/1.1\",\"HTTPS\":\"on\",\"HTTP_ACCEPT\":\"text\\/html,application\\/xhtml+xml,application\\/xml;q=0.9,image\\/webp,image\\/apng,*\\/*;q=0.8\",\"HTTP_ACCEPT_ENCODING\":\"gzip, deflate, br\",\"HTTP_ACCEPT_LANGUAGE\":\"en,en-US;q=0.8,en-GB;q=0.6\",\"HTTP_CONNECTION\":\"keep-alive\",\"HTTP_COOKIE\":\"camptix_client_stats=%7B%22visited_tickets_form%22%3Atrue%7D; wp-settings-1=hidetb%3D1%26editor%3Dhtml; wp-settings-time-1=1500446670; wordpress_sec_9d7b0e93dd644e59c08b7ec2f1b2892e=kdc%7C1501833723%7C1bmj7Cu7tBNxhFK5bX7sxAGqXL1f5wSXmlK8zXZA0pw%7C4722e5ca28caba01b9a76dfc1f21677b2823e7c31ce9f812baf12bcb919ba0b8; wordpress_logged_in_9d7b0e93dd644e59c08b7ec2f1b2892e=kdc%7C1501833723%7C1bmj7Cu7tBNxhFK5bX7sxAGqXL1f5wSXmlK8zXZA0pw%7C8ffd7fb30225af7cb27ed0b394ac621971ab4396367a5ad933636422f0f15f9b; PHPSESSID=nbb1gg2acpd9226oomh3kbdmq2; wp-saving-post=2-saved; ext_name=jaehkpjddfdgiiefcnhahapilbejohhj\",\"HTTP_HOST\":\"camptix.kdclabs.in\",\"HTTP_REFERER\":\"https:\\/\\/api.juspay.in\\/merchant\\/ipay?order_id=MOJO7726005A95615235&merchant_id=testing_instamojo&custom_stylesheet=https:\\/\\/s3.amazonaws.com:443\\/cache.podium.instamojo.com\\/assets\\/stylesheets\\/juspay-new-form-remote.c22043eda8c3.css\",\"HTTP_UPGRADE_INSECURE_REQUESTS\":\"1\",\"HTTP_USER_AGENT\":\"Mozilla\\/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/59.0.3071.115 Safari\\/537.36\",\"PATH\":\"\\/bin:\\/usr\\/bin\",\"QUERY_STRING\":\"tix_action=payment_return&tix_payment_token=dee2394ab86907d643cd757ed2ca98f4&tix_payment_method=instamojo&payment_id=MOJO7726005A95615235&payment_request_id=76730198218e489fba832231eb34c813\",\"REDIRECT_HTTPS\":\"on\",\"REDIRECT_QUERY_STRING\":\"tix_action=payment_return&tix_payment_token=dee2394ab86907d643cd757ed2ca98f4&tix_payment_method=instamojo&payment_id=MOJO7726005A95615235&payment_request_id=76730198218e489fba832231eb34c813\",\"REDIRECT_SSL_TLS_SNI\":\"camptix.kdclabs.in\",\"REDIRECT_STATUS\":\"200\",\"REDIRECT_UNIQUE_ID\":\"WXhCPbwxRHe73Ygr2358kgAAAA8\",\"REDIRECT_URL\":\"\\/indina-payments\\/\",\"REMOTE_ADDR\":\"182.58.55.215\",\"REMOTE_PORT\":\"50677\",\"REQUEST_METHOD\":\"GET\",\"REQUEST_SCHEME\":\"https\",\"SCRIPT_FILENAME\":\"\\/home\\/kdclabs\\/public_html\\/camptix\\/index.php\",\"SCRIPT_NAME\":\"\\/index.php\",\"SERVER_ADDR\":\"108.163.221.91\",\"SERVER_ADMIN\":\"webmaster@camptix.kdclabs.in\",\"SERVER_NAME\":\"camptix.kdclabs.in\",\"SERVER_PORT\":\"443\",\"SERVER_PROTOCOL\":\"HTTP\\/1.1\",\"SERVER_SIGNATURE\":\"\",\"SSL_TLS_SNI\":\"camptix.kdclabs.in\",\"TZ\":\"Asia\\/Kolkata\",\"UNIQUE_ID\":\"WXhCPbwxRHe73Ygr2358kgAAAA8\",\"PHP_SELF\":\"\\/index.php\",\"REQUEST_TIME_FLOAT\":\"1501053501.2921\",\"REQUEST_TIME\":\"1501053501\",\"argv\":[\"tix_action=payment_return&tix_payment_token=dee2394ab86907d643cd757ed2ca98f4&tix_payment_method=instamojo&payment_id=MOJO7726005A95615235&payment_request_id=76730198218e489fba832231eb34c813\"],\"argc\":\"1\"}', 'payment') made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, CampTix_Payment_Method_Instamojo->template_redirect, CampTix_Payment_Method_Instamojo->payment_return, CampTix_Payment_Method->__call, CampTix_Plugin->log, do_action('camptix_log_raw'), WP_Hook->do_action, WP_Hook->apply_filters, CampTix_Network_Tools->camptix_log_raw
> [26-Jul-2017 07:18:21 UTC] CampTix (camptix.kdclabs.in): Running payment_return. Server data attached.
===

**Comment by sanyogs** [comment]
Hello @vachan 

Thank you for video, but where i can see those error what you are represeting error_log. video shows ticket was suceesfully buy without any error.

**Comment by vachan** [comment]
@sanyog: Exactly what I had mentioned in:
> https://github.com/wpindiaorg/camptix-indian-payments/issues/14#issuecomment-317962628

But you still wanted a video, even after explain the videos will be useless as it is server level issue and the video will be pointless....

It is a the second value in the INSERT `object_id` is NULL, which is not valid.

**Comment by sanyogs** [comment]
@vachan i see you taken time to make video but why didnt you take more two miniute's add error log in video. so it will help that more.

As we have did all troubleshoot at our end and i did not notice this at my end, As well as @ravinderk if you can test this and let me know if you getting this at your end.

@vachan please comment this line in following file/inc/instamojo/class-camptix-payment-method-instamojo.php L270 'orderby'     => 'ID', where this we are not using.

Once you comment this and test it again and let me know is this getting you.

**Comment by sanyogs** [comment]
#29 has released for this please verify and merge.
