### ISSUE TITLE
Main file should be renamed to campt-indian-payment-gateway.php

### ISSUE THREAD

**Issue by claudiosanches** [wpindiaorg/camptix-indian-payments#16]
Since WordPress slug is `campt-indian-payment-gateway` in: https://wordpress.org/plugins/campt-indian-payment-gateway/

This also need to match the text domain #15

**Comment by vachan** [comment]
@claudiosanches : Is it possible to have a new slug on the WP.org repo?

Kindly suggest:
1) indian-payments-camptix _(preferred if valid)_
2) indian-payments-tix

So we can align the whole project and have a standard format, with least confusion, due to multiple naming parameters.

**SUGGESTION**: The word gateway - 1) Gives a different connotation, as in actual gateway and platform combination & 2) makes the length too long :-)

**Comment by claudiosanches** [comment]
It's not possible to change now, see: https://wordpress.org/plugins/developers/add/

> What will my plugin URL be?
> 
> Your plugin’s URL will be populated based on the value of Plugin Name in your main plugin file (the one with the plugin headers). If you set yours as Plugin Name: Boaty McBoatface then your URL will be https://wordpress.org/plugins/boaty-mcboatface and your slug will be boaty-mcboatface for example. If there is an existing plugin with your name, then you will be boaty-mcboatface-2 and so on. It behaves exactly like WordPress post names.
> 
> **Once your plugin is approved, it cannot be renamed.**

**Comment by claudiosanches** [comment]
Changing the plugin's main file can raise issues too, since will deactivate, so to prevent it need to keep the old file and use the follow code to prevent any problem:

```<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

// Update the main file.
$active_plugins = get_option( 'active_plugins', array() );

foreach ( $active_plugins as $key => $active_plugin ) {
	if ( strstr( $active_plugin, '/camptix-indian-payment.php' ) ) {
		$active_plugins[ $key ] = str_replace( '/camptix-indian-payment.php', '/campt-indian-payment-gateway.php', $active_plugin );
	}
}

update_option( 'active_plugins', $active_plugins );
```

But since have only less than 10 installations, this should not be a big problem.

**Comment by vachan** [comment]
Most or maybe all of those 10 installations are testing installations from the community helping test this community plugin! :-)

> https://make.wordpress.org/community/2017/07/21/recap-camptix-payment-gateways-for-indian-currency/

**Comment by claudiosanches** [comment]
Yes, right now should be just fine change the file name, but with more installations can be a support nightmare xD

**Comment by ravinderk** [comment]
@vachan File renamed
https://github.com/wpindiaorg/camptix-indian-payments/commit/f85160b8bfafa9fa313c400dd01f3e680a2901aa
