### ISSUE TITLE
Missing warning about minimum PHP version

### ISSUE THREAD

**Issue by claudiosanches** [wpindiaorg/camptix-indian-payments#17]
WordPress still supports PHP 5.2 and since this plugin uses 3rd party libraries that does not support 5.2 should be good include into the readme.txt a notice about it and maybe stop the plugin load if is not running the required PHP version.
Both should prevent PHP fatal errors.

**Comment by claudiosanches** [comment]
I'll test with https://github.com/wimg/PHPCompatibility tomorrow to make sure what is the minimum PHP version required, but from the Razorpay library should be 5.3+.

**Comment by raftaar1191** [comment]
We can set the Minimum PHP required of the plugin is 5.3 if not we can show an admin notices

**Comment by raftaar1191** [comment]
@claudiosanches 

Here is the PR of the above issue https://github.com/wpindiaorg/camptix-indian-payments/pull/28
