### ISSUE TITLE
Disabling Razor pay gives error

### ISSUE THREAD

**Issue by sanyogs** [wpindiaorg/camptix-indian-payments#18]
@ravinderk 

Please have look with this issue

Fatal error: Uncaught exception 'Razorpay\Api\Errors\BadRequestError' with message 'The api key provided is invalid' in /Applications/MAMP/htdocs/newpro/wp-content/plugins/campt-indian-payment-gateway/inc/razorpay/lib/razorpay-php/src/Request.php:123 Stack trace: #0 /Applications/MAMP/htdocs/newpro/wp-content/plugins/campt-indian-payment-gateway/inc/razorpay/lib/razorpay-php/src/Request.php(90): Razorpay\Api\Request->processError(Array, 401, Object(Requests_Response)) #1 /Applications/MAMP/htdocs/newpro/wp-content/plugins/campt-indian-payment-gateway/inc/razorpay/lib/razorpay-php/src/Request.php(44): Razorpay\Api\Request->checkErrors(Object(Requests_Response)) #2 /Applications/MAMP/htdocs/newpro/wp-content/plugins/campt-indian-payment-gateway/inc/razorpay/lib/razorpay-php/src/Entity.php(59): Razorpay\Api\Request->request('POST', 'orders/', Array) #3 /Applications/MAMP/htdocs/newpro/wp-content/plugins/campt-indian-payment-gateway/inc/razorpay/lib/razorpay-php/src/Entity.php(15): Razorpay\Api\Entity->request('POST', 'orders in /Applications/MAMP/htdocs/newpro/wp-content/plugins/campt-indian-payment-gateway/inc/razorpay/lib/razorpay-php/src/Request.php on line 123

To process troublshoot 
1> Remove all Razorpay Keys and disable Razorpay and try to add Instamojo gateway with test credentials
2> Once you try to book ticket it dont allow you to load form and though this Fatal Error

**Comment by ravinderk** [comment]
@sanyogs Fixed.
For Ref: https://github.com/wpindiaorg/camptix-indian-payments/commit/c2ed3d38aba841647089d84a0279433d7d6e4f02

**Comment by ravinderk** [comment]
@sanyogs closing for now. Let me know if still get this error
