### ISSUE TITLE
Validate Razorpay api key when saving settings.

### ISSUE THREAD

**Issue by ravinderk** [wpindiaorg/camptix-indian-payments#19]

**Comment by sanyogs** [comment]
it will be great on admin level it would validated those key provided by User

**Comment by claudiosanches** [comment]
I just submitted a Pull Requests to prevent fatal errors when using wrong API keys or for any other exception from Razorpay: https://github.com/wpindiaorg/camptix-indian-payments/pull/32
Maybe the message on the frontend should help already.

**Comment by ravinderk** [comment]
@claudiosanches Thank you for PR
