### ISSUE TITLE
Attendee Phone Number not displayed for editing.

### ISSUE THREAD

**Issue by vachan** [wpindiaorg/camptix-indian-payments#2]
When the ticket's **Edit Information** button is clicked, the **_Phone Number_** is not displayed.

**Comment by vachan** [comment]
Also at the backend, when editing the Attendee, the Phone Number is coming in duplicate.
https://cloudup.com/cLSRVJQ7FEA

Possible cause, phone number `function show_attendee_info()` is getting duplicated because it is present in both the class flies.

**Comment by vachan** [comment]
Such common functions like creating and displaying Phone Numbers must be in the primary file.

**Comment by sanyogs** [comment]
Phone Number function is creating dynamically, As if we called from primary file then it need to be static.
Where user need to created Phone Number as question from Camptix then user need to find out name value of this field and add it back to Plugin Setting.

**Comment by sanyogs** [comment]
By Default Camptix Allowed to Edit only those fields of tickets questions values which we created in Tickets.
So we will required Camptix Team to look over for this as we are creating Phone Number field though Jquery.

**Comment by vachan** [comment]
**TWO MORE ISSUES:**
1) We cannot force the user to only type in 10 Digit Phone Number, even if WordCamps are focused for Locals, but even international attendees are welcome.

2) The Phone Number does not get exported to the **_CSV_**

**Comment by sanyogs** [comment]
I have alternative option for this where i suggested name field of mobile question which will be in the Setup field for multiple gateway where we like to add Mobile field for gateway verification.

**Comment by vachan** [comment]
That is a task to explain every use who will be using the Plugin, incorporating it in the Plugin Functionality is the right way forward.

**Comment by vachan** [comment]
@sanyogs If Instamojo as a requirement of 10 digit number only, force the edit via `sub($phone,-10)` inside the _class-instamojo_ and pass it further. Don't force the attendee to work the options.
