### ISSUE TITLE
Razorpay: Two separate queries that both get the coupon?

### ISSUE THREAD

**Issue by coreymckrill** [wpindiaorg/camptix-indian-payments#24]
Maybe there's a good reason for this, but I couldn't work it out. In `razorpay_order_info()` there is this:

```php
// Get coupon detail.
		if ( ! empty( $coupon_id ) ) {
			// Get coupon.
			$coupon_id = $wpdb->get_var(
				$wpdb->prepare(
					"SELECT ID FROM $wpdb->posts WHERE post_title = %s",
					$coupon_id
				)
			);

			// Get coupon info.
			if ( ! empty( $coupon_id ) ) {
				$coupon            = get_post( $coupon_id );
				$coupon_percentage = get_post_meta( $coupon->ID, 'tix_discount_percent', true );
				$coupon_price      = get_post_meta( $coupon->ID, 'tix_discount_price', true );
			}
		}
```

As far as I can tell, `get_post( $coupon_id );` basically serves the same purpose as the custom SQL query that comes before it. Are they both necessary?

**Comment by ravinderk** [comment]
@coreymckrill I think you confuse by param name is used. In frontend, the attendee will use coupon title as the coupon code. Basically `$coupon_id` actually it is coupon code which I am using to detect coupon id.

![image](https://user-images.githubusercontent.com/1784821/28656391-4774aeca-72bf-11e7-945b-90a27b257c17.png)

**Comment by coreymckrill** [comment]
Ah, ok. It makes more sense with the changed variable name. Thanks.
