### ISSUE TITLE
Razorpay: Misc issues

### ISSUE THREAD

**Issue by coreymckrill** [wpindiaorg/camptix-indian-payments#25]
- [ ] **inc/razorpay/class-camptix-payment-method-razorpay.php:152** `array_map` can cause hidden problems if the variable in the second parameter is not actually an array. Make sure `$_POST['tix_tickets_selected']` is cast as an array.
- [ ] **inc/razorpay/class-camptix-payment-method-razorpay.php:291** Is there supposed to be an input field somewhere for `merchant_id`? It is checked in `validate_options` but not surfaced anywhere else.

**Comment by ravinderk** [comment]
@coreymckrill fixed.
For Ref: https://github.com/wpindiaorg/camptix-indian-payments/commit/9d2d5d945b8184526e3dbb7131a7e2da41b401c7
