### ISSUE TITLE
Instamojo: Test mode actually debits real funds?

### ISSUE THREAD

**Issue by coreymckrill** [wpindiaorg/camptix-indian-payments#26]
The description for the Sandbox Mode checkbox doesn't sound right to me:

> The Test Mode is a way to test payments. Any amount debited from your account should be re-credited within Five (5) working days.

Shouldn't there be a way to use a fake credit card number and simulate transactions in Sandbox mode without using real money? See https://support.instamojo.com/hc/en-us/articles/208485675-Test-or-Sandbox-Account

**Comment by sanyogs** [comment]
@coreymckrill 
I will remove this confusing sentence, As instamojo do not charge in sandbox mode if there are valid keys provided by admin for testing Instamojo in sandbox mode. End user can test gateway in sandbox mode with given [test credentials](https://support.instamojo.com/hc/en-us/articles/208485675-Test-or-Sandbox-Account)

**Comment by sanyogs** [comment]
#29 has released for this please verify and merge.
