### ISSUE TITLE
Instamojo: Misc issues

### ISSUE THREAD

**Issue by coreymckrill** [wpindiaorg/camptix-indian-payments#27]
- [ ] **inc/instamojo/class-camptix-payment-method-instamojo.php:40,44** When lines of code are commented out, add a comment on a separate line explaining the reason why the code is still there but disabled. Or just remove the commented out code.
- [ ] **inc/instamojo/class-camptix-payment-method-instamojo.php:124,125,180,182,188,189,212,241,257,283,284** Variables defined but never used. These make it harder to review the code and troubleshoot bugs in the future. Check to see if these should be used somewhere and remove if not needed.
- [ ] **inc/instamojo/class-camptix-payment-method-instamojo.php** Don't include the PHP closing tag at the end of the file. See https://stackoverflow.com/q/4410704

**Comment by sanyogs** [comment]
#29 has released for this please verify and merge.
