### ISSUE TITLE
New version for the plugin repo

### ISSUE THREAD

**Issue by coreymckrill** [wpindiaorg/camptix-indian-payments#34]
Now that @claudiosanches and I have completed our reviews and the issues created here have been resolved, we just need a new version tagged and uploaded to the repo:

https://wordpress.org/plugins/campt-indian-payment-gateway/

**Comment by sanyogs** [comment]
Hi Corey McKrill

I have update new repo files at https://wordpress.org/plugins/campt-indian-payment-gateway/

**Comment by coreymckrill** [comment]
@sanyogs Thanks. There is a discrepancy between the plugin code here on GitHub and the code in the wporg plugin repo.

The `razorpay-php` lib should be the built release version instead of the source, as described in #23. This was addressed with 3fe6e1f65041da0d49c4d04813d4b95b92f38afe, and the [master branch](https://github.com/wpindiaorg/camptix-indian-payments/tree/master/inc/razorpay/lib/razorpay-php) here has the correct code, but the version in the wporg repo still has the lib source:

https://plugins.trac.wordpress.org/browser/campt-indian-payment-gateway/tags/1.3/inc/razorpay/lib/razorpay-php

**Comment by sanyogs** [comment]
@coreymckrill 

I have Update Repo again on wporg as described in #23. This was addressed with 3fe6e1f

**Comment by coreymckrill** [comment]
Plugin installed :)
