### ISSUE TITLE
Minify/uglify JS with sourcemap

### ISSUE THREAD

**Issue by gagan0123** [wpindiaorg/camptix-indian-payments#39]
We can use Gulp Uglify to compress the JS and output the minified version with sourcemap in order to make it faster to serve and yet keeping it easier to debug

**Comment by ajitbohra** [comment]
Sounds good @ravinderk  @sanyogs your thoughts, would you like to take this up?

**Comment by sanyogs** [comment]
Its good idea, but review team process non minified version file. i have done this earlier but in review process, i asked to remove minified version and add non minified version file.
