### ISSUE TITLE
JavaScript breaks registration flow for Instamojo

### ISSUE THREAD

**Issue by coreymckrill** [wpindiaorg/camptix-indian-payments#41]
The **camptix-multi-popup.js** only applies to Razorpay currently, but it gets enqueued no matter which of the gateways are enabled. When Instamojo is the only enabled payment method, the script can prevent the Register button from submitting the form successfully.

This bug was discovered on the WordCamp Nashik 2017 site, which is using Instamojo, but not Razorpay.

### To reproduce:

* Enable Instamojo, but not Razorpay
* On the front end Tickets page, apply a coupon
* Then click the _Register_ button to start the checkout process

Clicking the button will cause the viewport to scroll down the Tickets page a ways, but otherwise do nothing.

### Suggested fix:

The quickest fix is to detect whether Razorpay is enabled, and only enqueue the script if it is. However, since it's possible that both Razorpay and Instamojo (and other future gateways added to the plugin) could all be enabled at the same time, a better fix would be to refine the script so that it only captures the Register button when completing the checkout using Razorpay.

**Comment by sanyogs** [comment]
Ok let me have look and update you soon on it.
