### ISSUE TITLE
Not redirecting to Instamojo if Event Name length is more the 30 Characters

### ISSUE THREAD

**Issue by deshabhishek007** [wpindiaorg/camptix-indian-payments#45]
Hi @sanyogs 

@iandunn  figured the cause of not redirecting to Instamojo, Here's the Link to suggestion.
https://wordpress.slack.com/archives/C08M59V3P/p1527013207000214

**Comment by iandunn** [comment]
It looks like `61caa3a` enforces a _minimum_ length for `purpose`, rather than restricting it to a `maximum` of `30` characters. I expected to see something like `substr( $productinfo, 0, 30 )` rather than `str_pad()`.

I haven't tested that, though. Am I missing something?

**Comment by iandunn** [comment]
cc @coreymckrill

**Comment by vachan** [comment]
I infreenced this from the slack conversation; and maybe misread that the minimum lenght required is 30.

Will go through the API docs in some time later!

**Comment by iandunn** [comment]
Ah, ok, it sounds like [it's a max rather than a min](https://wordpress.slack.com/archives/C08M59V3P/p1527012862000025):

> Looks like Instamojo's API is returning this error:

```'body' => string '{
    "success": false,
    "message": {
        "purpose": [
            "Ensure this field has no more than 30 characters."
        ]
    }```
