### ISSUE TITLE
Instamojo: Sandbox not resolved.

### ISSUE THREAD

**Issue by vachan** [wpindiaorg/camptix-indian-payments#5]
I am Still getting `Invalid Insatmojo Access Key & Token` in the **_sandbox mode_**
https://github.com/wpindiaorg/camptix-indian-payments/issues/1

**Comment by sanyogs** [comment]
Hello vachan

This error you get when you put Santbox into No, As provided credential is not for Live Gateway.
So hence its giving your Message 
`Invalid Insatmojo Access Key & Token`

So this is not the issue.
