### ISSUE TITLE
To Change GPL License from ver 3 to version 2.0 +

### ISSUE THREAD

**Issue by bombaypirate** [wpindiaorg/camptix-indian-payments#7]
So I know there is reasonable argument that GPL 2 and GPL 3 different significantly. So much so that Linux also users GPL 2 - and I think Automattic also is releasing software with the same ideas.

The general idea is the GPL2 and GPL 3 should be considered seperate types of licenses rather than  an iteration -

An explanation by Linus Torvalds here - https://www.youtube.com/watch?v=PaKIZ7gJlRU

**Comment by bombaypirate** [comment]
https://github.com/Automattic/_s/commits/master/LICENSE

An example of _S moving from ver 3 to ver 2.

**Comment by sanyogs** [comment]
i guess in plugin we have used following 
* License: GPLv2 or later
License file is initially created, as community we can take descision on it, And fixed the ver of license.

**Comment by vachan** [comment]
Updated to GPL v2
